import 'package:alice/alice.dart';
import 'package:alice_dio/alice_dio_adapter.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import '../../routes/app_router.dart';

// This file will be generated by build_runner
import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

@InjectableInit()
void configureDependencies() => getIt.init();

@module
abstract class RegisterModule {
  @lazySingleton
  AppRouter appRouter() => AppRouter();

  @singleton
  Alice alice() => Alice();

  @singleton
  AliceDioAdapter aliceDioAdapter(Alice alice) => AliceDioAdapter();
}